port: 3000
repositories:
  - name: example
    prefixes:
      - com.example
      - org.example
  - name: hello-world
    prefixes:
      - com.hello-world
  - name: 3rd-party
    prefixes: any
groups:
  - name: all
    repositories: all
    users:
      - name: example-rw
        permissions: rw
      - name: example-ro
        permissions: ro
users:
  - name: example-rw
    password: abcdefghijklmnopqrstuvwxyz
  - name: example-ro
    password: abcdefghijklmnopqrstuvwxyz
