port: 3000
repositories:
  - name: test
    path: /tmp/simple-repository-manager-it
    prefixes:
      - com.example
    users:
      - type: authenticated
        permissions: rw
users:
  - name: test
    password: simple-repository-manager-it
